export const supportedLanguages = [
    {code: "ar", name: "Arabic"},
    {code:"bn", name: "Bengali"},
    {code:"zh", name: "Chinese"},
    {code: "cs", name:"Czech"},
    {code: "da", name:"Danish"},
    {code: "en", name: "English" },
    {code: "en-IN", name: "English (India)"},
    {code:"fr", name: "French"},
    {code:"de", name: "German"},
    {code:"hi", name: "Hindi"},
    {code:"kn", name: "Kannada"},
    {code:"ml", name: "Malayalam"},
    {code: "ru", name: "Russian"},
    {code:"es", name: "Spanish"},
    {code: "ta", name: "Tamil"},
    {code: "uk", name: "Ukrainian"},
];